import type { Metadata } from 'next';
import './globals.css';

import { ThemeProvider } from '@/components/theme-provider';

import { Inter as FontSans } from 'next/font/google';
import { cn } from '@/lib/utils';
import { ModeToggle } from '@/components/ui/modeToggle';
export const fontSans = FontSans({
    subsets: ['latin'],
    variable: '--font-sans',
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang='en'>
            <body className={cn('min-h-screen bg-background font-sans antialiased', fontSans.variable)}>
                <ThemeProvider attribute='class' defaultTheme='system' enableSystem disableTransitionOnChange>
                    <div className='absolute top-5 right-5 sm:block hidden'>
                        <ModeToggle />
                    </div>
                    {children}
                </ThemeProvider>
            </body>
        </html>
    );
}
