apiVersion: apps/v1
kind: Deployment
metadata:
    name: api-gateway-depl
spec:
    replicas: 1
    selector:
        matchLabels:
            app: api-gateway
    template:
        metadata:
            labels:
                app: api-gateway
        spec:
            initContainers:
                - name: wait-for-nats
                  image: busybox
                  command: ['sh', '-c', 'until nc -z nats-srv 4222; do sleep 1; done']
            containers:
                - name: api-gateway
                  image: sharathchandranp/xsocial-api-gateway
                  env:
                      - name: NATS_CLIENT_ID
                        valueFrom:
                            fieldRef:
                                fieldPath: metadata.name
                      - name: NATS_URL
                        value: 'http://nats-srv:4222'
                      - name: 'NATS_CLUSTER_ID'
                        value: ecomm
                      - name: MONGO_URI
                        value: 'mongodb://api-gateway-mongo-srv:27017/api-gateway'
                      - name: JWT_KEY
                        valueFrom:
                            secretKeyRef:
                                name: jwt-secret
                                key: JWT_KEY
---
apiVersion: v1
kind: Service
metadata:
    name: api-gateway-srv
spec:
    selector:
        app: api-gateway
    ports:
        - name: api-gateway
          protocol: TCP
          port: 3000
          targetPort: 3000
