apiVersion: apps/v1
kind: Deployment
metadata:
    name: chat-depl
spec:
    replicas: 1
    selector:
        matchLabels:
            app: chat
    template:
        metadata:
            labels:
                app: chat
        spec:
            containers:
                - name: chat
                  image: sharathchandranp/xsocial-chat
                  env:
                      - name: NATS_CLIENT_ID
                        valueFrom:
                            fieldRef:
                                fieldPath: metadata.name
                      - name: NATS_URL
                        value: 'http://nats-srv:4222'
                      - name: 'NATS_CLUSTER_ID'
                        value: ecomm
                      - name: MONGO_URI
                        valueFrom:
                            secretKeyRef:
                                name: mongo-secret
                                key: MONGO_SECRET
                      - name: JWT_KEY
                        valueFrom:
                            secretKeyRef:
                                name: jwt-secret
                                key: JWT_KEY
---
apiVersion: v1
kind: Service
metadata:
    name: chat-srv
spec:
    selector:
        app: chat
    ports:
        - name: chat
          protocol: TCP
          port: 3000
          targetPort: 3000
