apiVersion: apps/v1
kind: Deployment
metadata:
    name: post-depl
spec:
    replicas: 1
    selector:
        matchLabels:
            app: post
    template:
        metadata:
            labels:
                app: post
        spec:
            containers:
                - name: post
                  image: sharathchandranp/xsocial-posts
                  env:
                      - name: NATS_CLIENT_ID
                        valueFrom:
                            fieldRef:
                                fieldPath: metadata.name
                      - name: NATS_URL
                        value: 'http://nats-srv:4222'
                      - name: 'NATS_CLUSTER_ID'
                        value: ecomm
                      - name: MONGO_URI
                        value: 'mongodb+srv://sharath-wq:i3x3j4bpfx@cluster0.xipfc3c.mongodb.net/xsocial'
                      - name: JWT_KEY
                        valueFrom:
                            secretKeyRef:
                                name: jwt-secret
                                key: JWT_KEY
---
apiVersion: v1
kind: Service
metadata:
    name: post-srv
spec:
    selector:
        app: post
    ports:
        - name: post
          protocol: TCP
          port: 3000
          targetPort: 3000
