name: deploy-notifications

on:
  push: 
    branches: 
      - main
    paths: 
      - 'notifications/**'

jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd notifications && docker build -t sharathchandranp/xsocial-notifications .
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env: 
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - run: docker push sharathchandranp/xsocial-notifications
      - uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - run: doctl kubernetes cluster kubeconfig save xsocail-cluster
      - run: kubectl rollout restart deployment notifications-depl
