name: deploy-api-gateway

on:
  push: 
    branches: 
      - prod
    paths: 
      - 'api-gateway/**'

jobs: 
 build:
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@v2
     - run: cd api-gateway && docker build -t sharathchandranp/xsocial-api-gateway .
     - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
       env: 
         DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
         DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
     - run: docker push sharathchandranp/xsocial-api-gateway
